export const anaUi = {
  recipeVersion: "tokens.v1",
  buttonSize: "md",
  buttonStyle: "solid",
  buttonGeometry: {
    border: 100,
    borderToken: "2xs",
    gapToken: "spaceXs",
    height: 100,
    paddingXToken: "spaceSm",
    paddingYToken: "space2xs",
    radiusToken: "2xs",
    shadowToken: "none",
    shadowMode: "outer",
  },
  buttonTransparent: {
    border: 0,
    opacity: 0,
  },
  button: {
    recipe: {
      levels: {
        "2xs": {
          gap: "space2xs",
          height: "2xs",
          icon: "2xs",
          minWidth: "2xs",
          motion: "sm",
          stateLayer: "2xs",
          surface: "2xs",
          text: "caption",
        },
        xs: {
          gap: "spaceXs",
          height: "xs",
          icon: "xs",
          minWidth: "xs",
          motion: "sm",
          stateLayer: "xs",
          surface: "xs",
          text: "label",
        },
        sm: {
          gap: "spaceXs",
          height: "sm",
          icon: "sm",
          minWidth: "sm",
          motion: "sm",
          stateLayer: "sm",
          surface: "sm",
          text: "label",
        },
        md: {
          gap: "spaceSm",
          height: "md",
          icon: "sm",
          minWidth: "md",
          motion: "sm",
          stateLayer: "sm",
          surface: "md",
          text: "label",
        },
      },
    },
  },
  cardGeometry: {
    borderToken: "sm",
    gapToken: "spaceMd",
    paddingXToken: "spaceXl",
    paddingYToken: "spaceXl",
    radiusToken: "2xs",
    shadowToken: "2xs",
  },
  badgeSize: "sm",
  badgeGeometry: {
    gapToken: "space2xs",
    paddingXToken: "spaceXs",
    radiusToken: "2xs",
  },
  surface: {
    appearance: "solid",
    tone: "neutral",
    shadow: 10,
    shadowMode: "outer",
  },
  text: {
    bodyFont: "body",
    bodySize: "md",
    bodyTone: "default",
    bodyWeight: "regular",
    h1Font: "heading",
    h1Size: "5xl",
    h1Weight: "bold",
    h2Font: "heading",
    h2Size: "3xl",
    h2Weight: "bold",
    h3Font: "heading",
    h3Size: "xl",
    h3Weight: "semibold",
    captionFont: "body",
    captionSize: "2xs",
    captionWeight: "semibold",
    captionLineHeight: "xs",
    labelFont: "body",
    labelSize: "xs",
    labelWeight: "semibold",
    labelLineHeight: "xs",
  },
};
